name: Link Checker

on:
  workflow_dispatch:

jobs:
  asciidoc-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm install -g asciidoc-link-check
    - run: find . -name \*.adoc -exec asciidoc-link-check -c config.json {} \;
